# Generated by Django 2.0.7 on 2020-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='image.jpg', upload_to='articles/'),
        ),
    ]
